### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by blezinski** [crouvpony47/furdown#1]
After login the authentication window goes to the furaffinity homepage and just sits there
![ss (2019-09-09 at 09 40 27)](https://user-images.githubusercontent.com/8310192/64530254-d15c3600-d34b-11e9-9455-7db4de968bde.png)
![ss (2019-09-09 at 09 46 08)](https://user-images.githubusercontent.com/8310192/64530269-d9b47100-d34b-11e9-8cca-674a7ff077dd.jpg)

**Comment by crouvpony47** [comment]
This happens when Cloudflare's "[I'm Under Attack](https://support.cloudflare.com/hc/en-us/articles/200170076-What-does-I-m-Under-Attack-Mode-do-)" mode is active. It imposes stricter checks on all site's clients, which this app won't pass (it's not impossible, but impractical to implement in reasonable time). As far as I know, FA is no longer under attack and this app functions normally at the moment.

Also, even though you can now find this statement on most of FA pages:

> Limit bot activity to periods with less than 10k registered users online.

I found no evidence that it's a hard limit (or we do a good enough job to pass as a legit user); when site is not in "I'm Under Attack" mode, furdown should function regardless of the number of registered users online.

I'm closing this issue for now, but feel free to reopen it in case bot traffic is to be limited under normal circumstances as well, or the authorization otherwise breaks.
