### ISSUE TITLE
Failed to make sure target directories do exist

### ISSUE THREAD

**Issue by AfxousaAjagara** [crouvpony47/furdown#12]
login is now successful, but now I get "Failed to make sure target directories do exist" error. Is there any way to give information for you to debug more better?
I try to download Cenegan024's gallary.

**Comment by AfxousaAjagara** [comment]
I just found that can't even download this example link too (https://www.furaffinity.net/gallery/jt47jade)

**Comment by AfxousaAjagara** [comment]
Strange...I delete everything related with furdown, re-download it and now it works again. more strange I literally doesn't touch anything except download link.

**Comment by crouvpony47** [comment]
It looks more like a permissions problem rather than something in the app itself.

To function normally, furdown needs write permissions for `%AppData%\furdown\furdown.conf` and the two directories that are selectable in the Settings tab (unless [portable mode](https://github.com/crouvpony47/furdown#portable-mode) is used). It will also likely **not** run from an insecure location like a SMB drive.

All I could think of is your antivirus software blocking some disk I/O on the first run, before it had a chance to check the safety.

Please let me know if you can reproduce this issue (and also include OS and antivirus software (if any) versions)

**Comment by AfxousaAjagara** [comment]
I'll tell you when I have same problem again. Thank you. I think you can close this issue now.

**Comment by crouvpony47** [comment]
Okay, closing for now then

*I've also tested on another vanilla version of Windows (Win10 1903, Windows Defender and SmartScreen on, x86) without much luck in terms of reproducing this.*
