### ISSUE TITLE
Feature Request - Download submission inbox

### ISSUE THREAD

**Issue by Zoodee** [crouvpony47/furdown#20]
Would be super handy if it's possible! Tried doing it just now but it seems to list pages forever.

**Comment by crouvpony47** [comment]
Are you talking about a page that displays art from the watched artists? If so, that's totally possible but I need to first learn how it works, since I rarely ever use the `+Watch`  thing and no one has requested this feature before either.

**Comment by Zoodee** [comment]
Yeah, that is what I meant, I wasn't entirely sure what to call it. Thank you for considering it! (Don't worry about it if it's too much work though.)

**Comment by crouvpony47** [comment]
I've implemented the foundation for this feature. Documentation and some sanity checks are not there yet, but it should now handle `https://www.furaffinity.net/msg/submissions/` as a valid gallery URL if you compile the latest source code [or download this beta build](https://www.mediafire.com/file/f74c4f654d55nru/furdown0512%252Bupd1beta.zip/file). I will greatly appreciate the feedback on how well it works, since I have a relatively empty submissions inbox and thus unable to test how it behaves at a larger scale.

**Comment by Zoodee** [comment]
I've tested it once so far and it worked great. I'll let my inbox build up for a few days to test it on larger amounts and get back to you. Thank you so much for implementing this!

**Comment by crouvpony47** [comment]
Fully implemented in [release v.0.5.2.0](https://github.com/crouvpony47/furdown/releases/tag/v.0.5.2.0)

If you find any problems in this implementation, please open a new issue
