### ISSUE TITLE
"broken filename detected, replacing with "unknown.jpg""

### ISSUE THREAD

**Issue by VanTuz5** [crouvpony47/furdown#21]
When I tried to download сrystal-for-ever's gallery, some of the files had "unknown" after the numbers, while the program writes  "broken filename detected, replacing with "unknown.jpg""

**Comment by crouvpony47** [comment]
Some old (think 2006) images use a different pattern for the filename, these are not currently parsed properly.  
Example of those would be  
`https://d.furaffinity.net/art/crystal-for-ever/scraps/1136511461/1136511461.crystal-for-ever.kissmelikenoothercopy.png`
under the modern naming scheme, this should have been
`https://d.furaffinity.net/art/crystal-for-ever/scraps/1136511461/1136511461.crystal-for-ever_kissmelikenoothercopy.png`

I will consider supporting this old scheme as well in the next update, but regardless some files will still be named `unknown.jpg`, as there is a surprisingly high amount of cases where the filename makes no sense whatsoever (having no extension, zero extension (i.e. ending with a `.`) and many other kinds of weirdness) --  `unknown.jpg` is still better than `123456.`.

Also, you can use an actual title instead of filenames by replacing `%FILEPART%` with `%TITLE%.%EXT%` in the patterns on the Settings tab. Extension will still be wrong for "broken" non-jpegs, but the name itself will usually make more sense.

**Comment by crouvpony47** [comment]
Implemented in [release v.0.5.2.0](https://github.com/crouvpony47/furdown/releases/tag/v.0.5.2.0)

`unknown.jpg` will only be used for irrecoverably broken filenames
